Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -32,7 +32,8 @@ jobs:
 
       - name: Save Docker image
         run: |
-          docker save 825765405225.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest -o image.tar
+          docker save -o image.tar 825765405225.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
+          ls -la  # List files to verify image.tar exists
 
   upload-to-s3:
     runs-on: ubuntu-latest
@@ -49,12 +50,19 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}
 
+      - name: Verify image.tar exists
+        run: |
+          ls -la  # Check if image.tar exists before uploading
+          if [ ! -f image.tar ]; then
+            echo "Error: image.tar not found"
+            exit 1
+          fi
+
       - name: Upload image to S3
         run: |
           aws s3 cp image.tar s3://$S3_BUCKET/image.tar
         env:
           S3_BUCKET: bhairavatv1
-
   deploy-to-eks:
     runs-on: ubuntu-latest
     needs: build-and-push-ecr
